# Generated by Django 3.0.5 on 2020-04-29 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.URLField(default='localhost:8000'),
        ),
    ]
