# Generated by Django 3.0.5 on 2020-04-29 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200428_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.CharField(default='https://wpdean.com/wp-content/uploads/2015/10/Useful-WordPress-Tools.jpg', max_length=1000),
        ),
    ]
